version: "3.8"

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    restart: always
    # create a volume in the db directory that is mounted to the container
    volumes:
      - ./db:/src/db
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.prod
    networks:
      - personal-inventory-app
  inventory-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=https://web:8000 # Reference the backend service by its name in the same network
    networks:
      - personal-inventory-app

networks:
  personal-inventory-app:
    external: true

volumes:
  db: